/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gscavo.veterinaryclinic.view.panels.register;

import javax.swing.*;

import lombok.Getter;
import org.gscavo.veterinaryclinic.model.abstractions.BaseModel;
import org.gscavo.veterinaryclinic.view.MainUserFrame;
import org.gscavo.veterinaryclinic.view.model_panel.abstractions.BaseInputPanel;

import java.awt.*;
import org.bson.types.ObjectId;
import org.gscavo.veterinaryclinic.utils.ViewUtils;
import org.gscavo.veterinaryclinic.utils.enums.Models;
import org.gscavo.veterinaryclinic.utils.information.SystemOperationResult;

/**
 *
 * @author gscavo
 */
public class RegisterPanel extends javax.swing.JPanel {

    private JFrame frame;
    private Models model;

    @Getter
    private BaseInputPanel baseInputPanel;

    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
    }
    
    public RegisterPanel(MainUserFrame mainUserFrame, Models model) {
        this.model = model;
        this.frame = mainUserFrame;
        initComponents();
        myInitComponents();
    }

    private <T extends BaseInputPanel> void myInitComponents() {
        try {
            this.baseInputPanel = (T) this.model.getInputPanelClass().getDeclaredConstructor().newInstance();
            if (mainPanel.getComponentCount() > 0) {
                mainPanel.removeAll();
            }
            mainPanel.add((JPanel) this.baseInputPanel, BorderLayout.CENTER);
            setCalculatedPreferredSize();
            ViewUtils.updateScreen(frame,false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void setCalculatedPreferredSize() {
        Dimension panelPreferredSize = ((JPanel) this.baseInputPanel).getPreferredSize();
        Dimension buttonRowPreferredSize = this.buttonRow.getPreferredSize();
        System.out.println("buttonRowPreferredSize.height: " + buttonRowPreferredSize.height);
        int width = panelPreferredSize.width;
        int height = buttonRowPreferredSize.height + panelPreferredSize.height;
        
        this.setPreferredSize(
                new Dimension(
                        width, 
                        height + 50
                )
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        buttonRow = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(420, 420));
        setSize(new java.awt.Dimension(420, 420));
        setLayout(new java.awt.BorderLayout());

        mainPanel.setRequestFocusEnabled(false);
        mainPanel.setLayout(new java.awt.BorderLayout());
        add(mainPanel, java.awt.BorderLayout.CENTER);

        buttonRow.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cancelButton.setText("Cancelar");
        cancelButton.setPreferredSize(new java.awt.Dimension(100, 25));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonRow.add(cancelButton);

        registerButton.setText("Cadastrar");
        registerButton.setPreferredSize(new java.awt.Dimension(100, 25));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        buttonRow.add(registerButton);

        add(buttonRow, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        ViewUtils.closeWindow(evt);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        SystemOperationResult<ObjectId> res = this.baseInputPanel.getMainController()
                .register((BaseModel<?>) this.baseInputPanel.getData());

        ViewUtils.showInformationDialog(this, res);

        myInitComponents();

    }//GEN-LAST:event_registerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonRow;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
