/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gscavo.veterinaryclinic.view.model_panel;

import lombok.Getter;
import org.gscavo.veterinaryclinic.controller.ClientController;
import org.gscavo.veterinaryclinic.model.Admin;
import org.gscavo.veterinaryclinic.model.Client;
import org.gscavo.veterinaryclinic.utils.enums.Controllers;
import org.gscavo.veterinaryclinic.utils.enums.PersonType;
import org.gscavo.veterinaryclinic.view.model_panel.abstractions.BaseInputPanel;

/**
 *
 * @author gscavo
 */
public class AdminInputPanel extends javax.swing.JPanel implements BaseInputPanel<Admin> {

    @Getter
    private ClientController mainController;
    
    /**
     * Creates new form ClientInputPanel
     */
    public AdminInputPanel() {
        initComponents();
        initControllers();
        myInitComponents();
        this.personInputPanel1.setData(new Admin());
    }
    
    public AdminInputPanel(Admin admin) {
        initComponents();
        initControllers();
        myInitComponents();
        this.personInputPanel1.setData(admin);
    }

    private void initControllers() {
        this.mainController = (ClientController) Controllers.getByName(Client.class);
    };

    private void myInitComponents() {
    }

    public Admin getData() {
        return (Admin) this.personInputPanel1.getData();
    }

    public void setData(Admin admin) {
        assert admin.getType() == PersonType.ADMIN;

        this.personInputPanel1.setData(admin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personInputPanel1 = new org.gscavo.veterinaryclinic.view.model_panel.abstractions.PersonInputPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personInputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(personInputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.gscavo.veterinaryclinic.view.model_panel.abstractions.PersonInputPanel personInputPanel1;
    // End of variables declaration//GEN-END:variables
}
