/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gscavo.veterinaryclinic.view.model_panel;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;
import javax.swing.DefaultComboBoxModel;
import lombok.Getter;
import lombok.Setter;
import org.bson.types.ObjectId;
import org.gscavo.veterinaryclinic.controller.*;
import org.gscavo.veterinaryclinic.model.*;
import org.gscavo.veterinaryclinic.utils.StringUtils;
import org.gscavo.veterinaryclinic.utils.ViewUtils;
import org.gscavo.veterinaryclinic.utils.enums.Controllers;
import org.gscavo.veterinaryclinic.utils.information.SystemOperationResult;
import org.gscavo.veterinaryclinic.view.dialog.OperationStatusDialog;
import org.gscavo.veterinaryclinic.view.model_panel.abstractions.BaseInputPanel;

/**
 *
 * @author gscavo
 */
public class AppointmentInputPanel extends javax.swing.JPanel implements BaseInputPanel<Appointment> {

    @Getter
    @Setter
    private Appointment data;

    @Getter
    private AppointmentController mainController;

    @Getter
    private ClientController clientController;
    
    @Getter
    private AnimalController animalController;

    @Getter
    private VeterinarianController veterinarianController;

    @Getter
    private SymptomController symptomController;

    @Getter
    private ProcedureController procedureController;

    private ArrayList<Veterinarian> veterinarians;
    private ArrayList<Client> clients;
    private ArrayList<Animal> animals;

    /**
     * Creates new form AddressInputPanel
     */
    public AppointmentInputPanel() {
        this.data = new Appointment();
        
        initControllers();
        initComponents();
        myInitComponents();
    }

    public AppointmentInputPanel(Appointment appointment) {
        this.data = appointment;
        
        initControllers();
        initComponents();
        myInitComponents();
    }
    

    private void initControllers() {
        this.mainController = (AppointmentController) Controllers.getByName(Appointment.class);
        this.clientController = (ClientController) Controllers.getByName(Client.class);
        this.animalController = (AnimalController) Controllers.getByName(Animal.class);
        this.veterinarianController = (VeterinarianController) Controllers.getByName(Veterinarian.class);
        this.symptomController = (SymptomController) Controllers.getByName(Symptom.class);
        this.procedureController = (ProcedureController) Controllers.getByName(Procedure.class);
    }
    
    private void myInitComponents() {

        this.appointmentDateSelection.setModel(
                new DefaultComboBoxModel<>(
                        this.mainController.getNextDates().toArray(new String[0])
                )
        );

        this.appointmentHourSelection.setModel(
                new DefaultComboBoxModel<>(
                        this.mainController.getHours().toArray(new String[0])
                )
        );

        this.veterinarians = this.veterinarianController.getAll();

        this.appointmentVeterinarianSelection.setModel(
                new DefaultComboBoxModel<>(
                        IntStream
                                .range(0, this.veterinarians.size())
                                .mapToObj(idx -> StringUtils.formatToSelection(idx, this.veterinarians.get(idx).getName()))
                                .toList()
                                .toArray(new String[0])
                )
        );

        this.clients = this.clientController.getAll();

        this.appointmentClientSelection.setModel(
                new DefaultComboBoxModel<>(
                    IntStream
                        .range(0, this.clients.size())
                        .mapToObj(idx -> StringUtils.formatToSelection(idx, this.clients.get(idx).getName()))
                        .toList()
                        .toArray(new String[0])
                            
                )
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appointmentHeaderLabel = new javax.swing.JLabel();
        appointmentPriceLabel = new javax.swing.JLabel();
        appointmentDateLabel = new javax.swing.JLabel();
        appointmentAnimalLabel = new javax.swing.JLabel();
        appointmentVeterinarianLabel = new javax.swing.JLabel();
        headerSeparator = new javax.swing.JSeparator();
        appointmentTutorLabel = new javax.swing.JLabel();
        appointmentAnimalSelection = new javax.swing.JComboBox<>();
        appointmentVeterinarianSelection = new javax.swing.JComboBox<>();
        appointmentPriceInputField = new javax.swing.JSpinner();
        appointmentDateSelection = new javax.swing.JComboBox<>();
        appointmentDateLabel1 = new javax.swing.JLabel();
        appointmentHourSelection = new javax.swing.JComboBox<>();
        appointmentClientSelection = new javax.swing.JComboBox<>();

        appointmentHeaderLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        appointmentHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointmentHeaderLabel.setText("Consulta");
        appointmentHeaderLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        appointmentHeaderLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        appointmentHeaderLabel.setSize(new java.awt.Dimension(150, 30));

        appointmentPriceLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        appointmentPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointmentPriceLabel.setText("Preço");
        appointmentPriceLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        appointmentPriceLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        appointmentPriceLabel.setSize(new java.awt.Dimension(150, 30));

        appointmentDateLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        appointmentDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointmentDateLabel.setText("Data");
        appointmentDateLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        appointmentDateLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        appointmentDateLabel.setSize(new java.awt.Dimension(150, 30));

        appointmentAnimalLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        appointmentAnimalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointmentAnimalLabel.setText("Animal");
        appointmentAnimalLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        appointmentAnimalLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        appointmentAnimalLabel.setSize(new java.awt.Dimension(150, 30));

        appointmentVeterinarianLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        appointmentVeterinarianLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointmentVeterinarianLabel.setText("Veterinário");
        appointmentVeterinarianLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        appointmentVeterinarianLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        appointmentVeterinarianLabel.setSize(new java.awt.Dimension(150, 30));

        appointmentTutorLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        appointmentTutorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointmentTutorLabel.setText("Tutor");
        appointmentTutorLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        appointmentTutorLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        appointmentTutorLabel.setSize(new java.awt.Dimension(150, 30));

        appointmentAnimalSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Cliente" }));
        appointmentAnimalSelection.setFocusCycleRoot(true);
        appointmentAnimalSelection.setPreferredSize(new java.awt.Dimension(300, 30));
        appointmentAnimalSelection.setSize(new java.awt.Dimension(300, 30));
        appointmentAnimalSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentAnimalSelectionActionPerformed(evt);
            }
        });

        appointmentVeterinarianSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERROR" }));
        appointmentVeterinarianSelection.setPreferredSize(new java.awt.Dimension(300, 30));
        appointmentVeterinarianSelection.setSize(new java.awt.Dimension(300, 30));
        appointmentVeterinarianSelection.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                appointmentVeterinarianSelectionFocusGained(evt);
            }
        });
        appointmentVeterinarianSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentVeterinarianSelectionActionPerformed(evt);
            }
        });

        appointmentPriceInputField.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
        appointmentPriceInputField.setPreferredSize(new java.awt.Dimension(300, 30));
        appointmentPriceInputField.setSize(new java.awt.Dimension(300, 30));

        appointmentDateSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERROR" }));
        appointmentDateSelection.setPreferredSize(new java.awt.Dimension(300, 30));
        appointmentDateSelection.setSize(new java.awt.Dimension(300, 30));
        appointmentDateSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentDateSelectionActionPerformed(evt);
            }
        });

        appointmentDateLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        appointmentDateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointmentDateLabel1.setText("Horário");
        appointmentDateLabel1.setMaximumSize(new java.awt.Dimension(150, 30));
        appointmentDateLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        appointmentDateLabel1.setSize(new java.awt.Dimension(150, 30));

        appointmentHourSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERROR" }));
        appointmentHourSelection.setPreferredSize(new java.awt.Dimension(300, 30));
        appointmentHourSelection.setSize(new java.awt.Dimension(300, 30));

        appointmentClientSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERROR" }));
        appointmentClientSelection.setPreferredSize(new java.awt.Dimension(300, 30));
        appointmentClientSelection.setSize(new java.awt.Dimension(300, 30));
        appointmentClientSelection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                appointmentClientSelectionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(appointmentHeaderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(appointmentAnimalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(appointmentAnimalSelection, 0, 312, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(appointmentDateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(appointmentPriceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(appointmentDateLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                                .addComponent(appointmentVeterinarianLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(appointmentTutorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appointmentVeterinarianSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appointmentPriceInputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appointmentDateSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appointmentHourSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appointmentClientSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appointmentHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointmentPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentPriceInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointmentDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentDateSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointmentDateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentHourSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentVeterinarianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentVeterinarianSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentTutorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentClientSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointmentAnimalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentAnimalSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void appointmentDateSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentDateSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentDateSelectionActionPerformed

    private void appointmentAnimalSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentAnimalSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentAnimalSelectionActionPerformed

    private void appointmentVeterinarianSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentVeterinarianSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentVeterinarianSelectionActionPerformed

    private void appointmentVeterinarianSelectionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_appointmentVeterinarianSelectionFocusGained
        new OperationStatusDialog(
            (Frame) this.getTopLevelAncestor(),
            true,
            SystemOperationResult.failedToUpdateResourceSOR(Appointment.class)
        );
    }//GEN-LAST:event_appointmentVeterinarianSelectionFocusGained

    private void appointmentClientSelectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_appointmentClientSelectionItemStateChanged
        Client selected = this.clients.get(
                this.appointmentClientSelection.getSelectedIndex()
        );
        
        this.data.setClientId(
                selected
                .getId()
        );
        
        this.animals = animalController.getAllByClientId(selected.getId());

        this.appointmentAnimalSelection.setModel(
               new DefaultComboBoxModel<>(
                       IntStream
                               .range(0, this.animals.size())
                       .mapToObj(idx -> StringUtils.formatToSelection(idx, this.animals.get(idx).getName()))
                       .toList()
                       .toArray(new String[0])
               )
        );
    }//GEN-LAST:event_appointmentClientSelectionItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appointmentAnimalLabel;
    private javax.swing.JComboBox<String> appointmentAnimalSelection;
    private javax.swing.JComboBox<String> appointmentClientSelection;
    private javax.swing.JLabel appointmentDateLabel;
    private javax.swing.JLabel appointmentDateLabel1;
    private javax.swing.JComboBox<String> appointmentDateSelection;
    private javax.swing.JLabel appointmentHeaderLabel;
    private javax.swing.JComboBox<String> appointmentHourSelection;
    private javax.swing.JSpinner appointmentPriceInputField;
    private javax.swing.JLabel appointmentPriceLabel;
    private javax.swing.JLabel appointmentTutorLabel;
    private javax.swing.JLabel appointmentVeterinarianLabel;
    private javax.swing.JComboBox<String> appointmentVeterinarianSelection;
    private javax.swing.JSeparator headerSeparator;
    // End of variables declaration//GEN-END:variables
}
