/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gscavo.veterinaryclinic.view.model_panel;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import lombok.Getter;
import lombok.Setter;
import org.gscavo.veterinaryclinic.model.Client;
import org.gscavo.veterinaryclinic.model.simpleModels.PersonXAddress;
import org.gscavo.veterinaryclinic.view.model_panel.abstractions.BaseInputPanel;

/**
 *
 * @author gscavo
 */
public class ClientInputPanel extends javax.swing.JPanel {

    @Getter @Setter
    private PersonXAddress<Client> data;
    
    /**
     * Creates new form ClientInputPanel
     */
    public ClientInputPanel() {
        initComponents();
        
        myInitComponents();
    }
    
    private void myInitComponents() {
        this.userInputPanel1.addPropertyChangeListener(BaseInputPanel.DATA_PROPERTY_KEY, new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                changedData(evt);
            }
        });
    }

    private void changedData(PropertyChangeEvent evt) {        
        this.data = (PersonXAddress<Client>) this.userInputPanel1.getData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInputPanel1 = new org.gscavo.veterinaryclinic.view.model_panel.UserInputPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userInputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userInputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.gscavo.veterinaryclinic.view.model_panel.UserInputPanel userInputPanel1;
    // End of variables declaration//GEN-END:variables
}
