/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gscavo.veterinaryclinic.view.model_panel;

import lombok.Data;
import lombok.Getter;
import org.gscavo.veterinaryclinic.view.model_panel.abstractions.BaseInputPanel;

/**
 *
 * @author gscavo
 */
public class InternalPasswordInputPanel extends javax.swing.JPanel implements BaseInputPanel<String> {

    @Getter
    private String data;

    @Getter
    private String password;
    
    @Getter
    private String retypedPassword;
    
    /**
     * Creates new form AddressInputPanel
     */
    public InternalPasswordInputPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        procedureTypeButtonGroup = new javax.swing.ButtonGroup();
        passwordHeaderLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordInputField = new javax.swing.JTextField();
        headerSeparator = new javax.swing.JSeparator();
        retypePasswordLabel = new javax.swing.JLabel();
        retypePasswordInputField = new javax.swing.JTextField();

        passwordHeaderLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        passwordHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordHeaderLabel.setText("Credenciais");
        passwordHeaderLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        passwordHeaderLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        passwordHeaderLabel.setSize(new java.awt.Dimension(150, 30));

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Senha");
        passwordLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        passwordLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        passwordLabel.setSize(new java.awt.Dimension(150, 30));

        passwordInputField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordInputField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        passwordInputField.setPreferredSize(new java.awt.Dimension(150, 30));
        passwordInputField.setSize(new java.awt.Dimension(300, 30));
        passwordInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordInputFieldKeyReleased(evt);
            }
        });

        retypePasswordLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        retypePasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        retypePasswordLabel.setText("Confirme sua senha");
        retypePasswordLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        retypePasswordLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        retypePasswordLabel.setSize(new java.awt.Dimension(150, 30));

        retypePasswordInputField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        retypePasswordInputField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        retypePasswordInputField.setPreferredSize(new java.awt.Dimension(150, 30));
        retypePasswordInputField.setSize(new java.awt.Dimension(300, 30));
        retypePasswordInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                retypePasswordInputFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerSeparator)
                    .addComponent(passwordHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(retypePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(retypePasswordInputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passwordHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retypePasswordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retypePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passwordInputFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordInputFieldKeyReleased
        this.password = passwordInputField.getText();
    }//GEN-LAST:event_passwordInputFieldKeyReleased

    private void retypePasswordInputFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_retypePasswordInputFieldKeyReleased
        this.retypedPassword = retypePasswordInputField.getText();
    }//GEN-LAST:event_retypePasswordInputFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JLabel passwordHeaderLabel;
    private javax.swing.JTextField passwordInputField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.ButtonGroup procedureTypeButtonGroup;
    private javax.swing.JTextField retypePasswordInputField;
    private javax.swing.JLabel retypePasswordLabel;
    // End of variables declaration//GEN-END:variables
}
