/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gscavo.veterinaryclinic.view.model_panel;

import lombok.Getter;
import org.gscavo.veterinaryclinic.controller.ProcedureController;
import org.gscavo.veterinaryclinic.model.Procedure;
import org.gscavo.veterinaryclinic.utils.ViewUtils;
import org.gscavo.veterinaryclinic.utils.enums.Controllers;
import org.gscavo.veterinaryclinic.utils.enums.ProcedureType;
import org.gscavo.veterinaryclinic.view.model_panel.abstractions.BaseInputPanel;

/**
 *
 * @author gscavo
 */
public class ProcedureInputPanel extends javax.swing.JPanel implements BaseInputPanel<Procedure> {

    @Getter
    private Procedure data;
    
    @Getter
    private ProcedureController mainController;
    
    /**
     * Creates new form AddressInputPanel
     */
    public ProcedureInputPanel() {
        initComponents();
        initControllers();
        this.data = new Procedure();
    }
    
    public ProcedureInputPanel(Procedure procedure) {
        initComponents();
        initControllers();
        this.data = procedure;
    }

    private void initControllers() {
        this.mainController = (ProcedureController) Controllers.getByName(Procedure.class);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        procedureTypeButtonGroup = new javax.swing.ButtonGroup();
        procedureHeaderLabel = new javax.swing.JLabel();
        procedureNameLabel = new javax.swing.JLabel();
        procedurePriceLabel = new javax.swing.JLabel();
        procedureDescriptionLabel = new javax.swing.JLabel();
        procedureTypeLabel = new javax.swing.JLabel();
        procedureNameInputField = new javax.swing.JTextField();
        procedurePriceInputField = new javax.swing.JSpinner();
        headerSeparator = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        procedureDescriptionTextArea = new javax.swing.JTextArea();
        treatmentRadioButton = new javax.swing.JRadioButton();
        examRadioButton = new javax.swing.JRadioButton();

        procedureHeaderLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        procedureHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procedureHeaderLabel.setText("Procedimento");
        procedureHeaderLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        procedureHeaderLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        procedureHeaderLabel.setSize(new java.awt.Dimension(150, 30));

        procedureNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        procedureNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procedureNameLabel.setText("Nome");
        procedureNameLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        procedureNameLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        procedureNameLabel.setSize(new java.awt.Dimension(150, 30));

        procedurePriceLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        procedurePriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procedurePriceLabel.setText("Preço");
        procedurePriceLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        procedurePriceLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        procedurePriceLabel.setSize(new java.awt.Dimension(150, 30));

        procedureDescriptionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        procedureDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procedureDescriptionLabel.setText("Descrição");
        procedureDescriptionLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        procedureDescriptionLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        procedureDescriptionLabel.setSize(new java.awt.Dimension(150, 30));

        procedureTypeLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        procedureTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procedureTypeLabel.setText("Tipo");
        procedureTypeLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        procedureTypeLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        procedureTypeLabel.setSize(new java.awt.Dimension(150, 30));

        procedureNameInputField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        procedureNameInputField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        procedureNameInputField.setPreferredSize(new java.awt.Dimension(300, 30));
        procedureNameInputField.setSize(new java.awt.Dimension(300, 30));
        procedureNameInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                procedureNameInputFieldKeyReleased(evt);
            }
        });

        procedurePriceInputField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        procedurePriceInputField.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
        procedurePriceInputField.setPreferredSize(new java.awt.Dimension(300, 30));
        procedurePriceInputField.setSize(new java.awt.Dimension(300, 30));
        procedurePriceInputField.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                procedurePriceInputFieldStateChanged(evt);
            }
        });

        procedureDescriptionTextArea.setColumns(20);
        procedureDescriptionTextArea.setRows(5);
        procedureDescriptionTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                procedureDescriptionTextAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(procedureDescriptionTextArea);

        procedureTypeButtonGroup.add(treatmentRadioButton);
        treatmentRadioButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        treatmentRadioButton.setSelected(true);
        treatmentRadioButton.setText("Tratamento");
        treatmentRadioButton.setMaximumSize(new java.awt.Dimension(150, 50));
        treatmentRadioButton.setMinimumSize(new java.awt.Dimension(100, 20));
        treatmentRadioButton.setPreferredSize(new java.awt.Dimension(141, 30));
        treatmentRadioButton.setSize(new java.awt.Dimension(141, 30));
        treatmentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentRadioButtonActionPerformed(evt);
            }
        });

        procedureTypeButtonGroup.add(examRadioButton);
        examRadioButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        examRadioButton.setText("Exame");
        examRadioButton.setMaximumSize(new java.awt.Dimension(150, 50));
        examRadioButton.setMinimumSize(new java.awt.Dimension(100, 20));
        examRadioButton.setPreferredSize(new java.awt.Dimension(141, 30));
        examRadioButton.setSize(new java.awt.Dimension(141, 30));
        examRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(procedurePriceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addComponent(procedureNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(procedureTypeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(procedurePriceInputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(treatmentRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(examRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(procedureNameInputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(headerSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(procedureDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addComponent(procedureHeaderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(procedureHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(procedureNameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procedureNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(procedurePriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(procedurePriceInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(procedureTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(treatmentRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(examRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(procedureDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void procedureNameInputFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_procedureNameInputFieldKeyReleased
        this.data.setName(
            procedureNameInputField.getText()
        );
    }//GEN-LAST:event_procedureNameInputFieldKeyReleased

    private void procedurePriceInputFieldStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_procedurePriceInputFieldStateChanged
        this.data.setPrice(
                ViewUtils.getFloatFromJSpinner(this.procedurePriceInputField)
        );
    }//GEN-LAST:event_procedurePriceInputFieldStateChanged

    private void treatmentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentRadioButtonActionPerformed
        this.data.setType(
                ProcedureType.TREATMENT
        );
    }//GEN-LAST:event_treatmentRadioButtonActionPerformed

    private void examRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examRadioButtonActionPerformed
        this.data.setType(
                ProcedureType.EXAM
        );
    }//GEN-LAST:event_examRadioButtonActionPerformed

    private void procedureDescriptionTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_procedureDescriptionTextAreaKeyReleased
        this.data.setDescription(
                this.procedureDescriptionTextArea.getText()
        );
    }//GEN-LAST:event_procedureDescriptionTextAreaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton examRadioButton;
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel procedureDescriptionLabel;
    private javax.swing.JTextArea procedureDescriptionTextArea;
    private javax.swing.JLabel procedureHeaderLabel;
    private javax.swing.JTextField procedureNameInputField;
    private javax.swing.JLabel procedureNameLabel;
    private javax.swing.JSpinner procedurePriceInputField;
    private javax.swing.JLabel procedurePriceLabel;
    private javax.swing.ButtonGroup procedureTypeButtonGroup;
    private javax.swing.JLabel procedureTypeLabel;
    private javax.swing.JRadioButton treatmentRadioButton;
    // End of variables declaration//GEN-END:variables
}
