/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gscavo.veterinaryclinic.view.model_panel;

import lombok.Getter;
import lombok.Setter;
import org.gscavo.veterinaryclinic.controller.SymptomController;
import org.gscavo.veterinaryclinic.model.Symptom;
import org.gscavo.veterinaryclinic.utils.enums.Controllers;
import org.gscavo.veterinaryclinic.view.model_panel.abstractions.BaseInputPanel;

/**
 *
 * @author gscavo
 */
public class SymptomInputPanel extends javax.swing.JPanel implements BaseInputPanel<Symptom>{

    @Getter
    @Setter
    private Symptom data;

    @Getter
    private SymptomController mainController;

    /**
     * Creates new form AddressInputPanel
     */
    public SymptomInputPanel() {
        initComponents();
        initControllers();
        this.data = new Symptom();
    }
    
    public SymptomInputPanel(Symptom symptom) {
        initComponents();
        initControllers();
        this.data = symptom;
    }

    private void initControllers() {
        this.mainController = (SymptomController) Controllers.getByName(Symptom.class);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        procedureTypeButtonGroup = new javax.swing.ButtonGroup();
        symptomsHeaderLabel = new javax.swing.JLabel();
        symptomsDescriptionLabel = new javax.swing.JLabel();
        headerSeparator = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        symptomsDescriptionTextArea = new javax.swing.JTextArea();

        symptomsHeaderLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        symptomsHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        symptomsHeaderLabel.setText("Sintomas");
        symptomsHeaderLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        symptomsHeaderLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        symptomsHeaderLabel.setSize(new java.awt.Dimension(150, 30));

        symptomsDescriptionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        symptomsDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        symptomsDescriptionLabel.setText("Descrição");
        symptomsDescriptionLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        symptomsDescriptionLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        symptomsDescriptionLabel.setSize(new java.awt.Dimension(150, 30));

        symptomsDescriptionTextArea.setColumns(20);
        symptomsDescriptionTextArea.setRows(5);
        symptomsDescriptionTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                symptomsDescriptionTextAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(symptomsDescriptionTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(symptomsDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                    .addComponent(symptomsHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerSeparator))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(symptomsHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(symptomsDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void symptomsDescriptionTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_symptomsDescriptionTextAreaKeyReleased
        this.data.setDescription(
                this.symptomsDescriptionTextArea.getText()
        );
    }//GEN-LAST:event_symptomsDescriptionTextAreaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup procedureTypeButtonGroup;
    private javax.swing.JLabel symptomsDescriptionLabel;
    private javax.swing.JTextArea symptomsDescriptionTextArea;
    private javax.swing.JLabel symptomsHeaderLabel;
    // End of variables declaration//GEN-END:variables
}
