/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gscavo.veterinaryclinic.view.model_panel;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import lombok.Getter;
import lombok.Setter;
import org.gscavo.veterinaryclinic.controller.UserController;
import org.gscavo.veterinaryclinic.model.User;
import org.gscavo.veterinaryclinic.model.abstractions.Person;
import org.gscavo.veterinaryclinic.model.simpleModels.PersonXAddress;
import org.gscavo.veterinaryclinic.utils.enums.Controllers;
import org.gscavo.veterinaryclinic.view.model_panel.abstractions.BaseInputPanel;

/**
 *
 * @author gscavo
 */
public class UserInputPanel extends javax.swing.JPanel implements BaseInputPanel<PersonXAddress<?>> {

    @Getter
    private UserController mainController;
    
    @Getter
    @Setter
    private PersonXAddress<?> data;

    /**
     * Creates new form UserInputPanel
     */
    public UserInputPanel() {
        initComponents();
        initControllers();
        myInitComponents();
    }

    public <T extends Person> UserInputPanel(PersonXAddress<T> personXAddress) {
        initComponents();
        initControllers();
        myInitComponents();

        this.personInputPanel.setData(personXAddress.getPerson());
        this.addressInputPanel.setData(personXAddress.getAddress());
    }

    private void initControllers() {
        this.mainController = (UserController) Controllers.getByName("USER");
    }

    private void myInitComponents() {
        this.personInputPanel.addPropertyChangeListener(DATA_PROPERTY_KEY, new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                dataChangedOnPersonInputPanel(evt);
            }
        });
        this.addressInputPanel.addPropertyChangeListener(DATA_PROPERTY_KEY, new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                dataChangedOnAddressPanel(evt);
            }
        });
    }

    private void dataChangedOnPersonInputPanel(PropertyChangeEvent evt) {
        this.data.getPerson().fill(
                this.personInputPanel.getData()
        );
    }
    
    private void dataChangedOnAddressPanel(PropertyChangeEvent evt) {
        this.data.setAddress(this.getData().getAddress());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addressInputPanel = new org.gscavo.veterinaryclinic.view.model_panel.AddressInputPanel();
        personInputPanel = new org.gscavo.veterinaryclinic.view.model_panel.abstractions.PersonInputPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personInputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addComponent(addressInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(personInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.gscavo.veterinaryclinic.view.model_panel.AddressInputPanel addressInputPanel;
    private org.gscavo.veterinaryclinic.view.model_panel.abstractions.PersonInputPanel personInputPanel;
    // End of variables declaration//GEN-END:variables
}
