/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gscavo.veterinaryclinic.view.model_panel;

/**
 *
 * @author gscavo
 */
public class VeterinarianInputPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddressInputPanel
     */
    public VeterinarianInputPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        procedureTypeButtonGroup = new javax.swing.ButtonGroup();
        veterinarianDataHeaderLabel = new javax.swing.JLabel();
        veterinariamCrmvLabel = new javax.swing.JLabel();
        veterinarianCrmvInputField = new javax.swing.JTextField();
        headerSeparator = new javax.swing.JSeparator();

        veterinarianDataHeaderLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        veterinarianDataHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        veterinarianDataHeaderLabel.setText("Dados do Veterinário");
        veterinarianDataHeaderLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        veterinarianDataHeaderLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        veterinarianDataHeaderLabel.setSize(new java.awt.Dimension(150, 30));

        veterinariamCrmvLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        veterinariamCrmvLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        veterinariamCrmvLabel.setText("CRMV");
        veterinariamCrmvLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        veterinariamCrmvLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        veterinariamCrmvLabel.setSize(new java.awt.Dimension(150, 30));

        veterinarianCrmvInputField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        veterinarianCrmvInputField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        veterinarianCrmvInputField.setPreferredSize(new java.awt.Dimension(150, 30));
        veterinarianCrmvInputField.setSize(new java.awt.Dimension(300, 30));
        veterinarianCrmvInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veterinarianCrmvInputFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerSeparator)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(veterinariamCrmvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(veterinarianCrmvInputField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(veterinarianDataHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(veterinarianDataHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(veterinarianCrmvInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veterinariamCrmvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void veterinarianCrmvInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veterinarianCrmvInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veterinarianCrmvInputFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.ButtonGroup procedureTypeButtonGroup;
    private javax.swing.JLabel veterinariamCrmvLabel;
    private javax.swing.JTextField veterinarianCrmvInputField;
    private javax.swing.JLabel veterinarianDataHeaderLabel;
    // End of variables declaration//GEN-END:variables
}
