/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.gscavo.veterinaryclinic.view.panels;

/**
 *
 * @author gscavo
 */
public class todayAppointments extends javax.swing.JPanel {

    /**
     * Creates new form todayAppointments
     */
    public todayAppointments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        leftTabbedPanel = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        databaseTable = new javax.swing.JTable();
        rightPanel = new javax.swing.JPanel();
        appointmentViewPanel = new org.gscavo.veterinaryclinic.view.model_panel.AppointmentInputPanel();
        buttonRow = new javax.swing.JPanel();
        clientAppearedButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 2));

        databaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(databaseTable);

        leftTabbedPanel.addTab("tab3", jScrollPane1);

        add(leftTabbedPanel);

        rightPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rightPanel.setLayout(new java.awt.BorderLayout());

        appointmentViewPanel.setEnabled(false);
        appointmentViewPanel.setFocusable(false);
        rightPanel.add(appointmentViewPanel, java.awt.BorderLayout.CENTER);

        buttonRow.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        buttonRow.setPreferredSize(new java.awt.Dimension(460, 80));
        buttonRow.setSize(new java.awt.Dimension(100, 80));
        buttonRow.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        clientAppearedButton.setText("Presente");
        buttonRow.add(clientAppearedButton);

        jButton3.setText("Adicionar Procedimento");
        buttonRow.add(jButton3);

        jButton2.setText("Não Veio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buttonRow.add(jButton2);

        jButton1.setText("Adicionar Sintomas");
        jButton1.setToolTipText("");
        buttonRow.add(jButton1);

        rightPanel.add(buttonRow, java.awt.BorderLayout.PAGE_END);

        add(rightPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.gscavo.veterinaryclinic.view.model_panel.AppointmentInputPanel appointmentViewPanel;
    private javax.swing.JPanel buttonRow;
    private javax.swing.JButton clientAppearedButton;
    private javax.swing.JTable databaseTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane leftTabbedPanel;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
